# Generated by Django 5.1.6 on 2025-03-06 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands_of_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Brands_of_equipments',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipments/')),
            ],
            options={
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='Manafacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='manafacturers/')),
            ],
            options={
                'verbose_name_plural': 'Manafacturers',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.CreateModel(
            name='Filter_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='main.filter_type')),
            ],
            options={
                'verbose_name_plural': 'Filter_types',
            },
        ),
        migrations.CreateModel(
            name='Oil_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('bp_opening_dp', models.FloatField(help_text='БПВ открытие ДП (фунтов на квадратный дюйм)')),
                ('inner_gasket_diameter', models.FloatField(help_text='Внутренний диаметр прокладки (дюймы)')),
                ('largest_od', models.FloatField(help_text='Крупнейший OD (дюймы)')),
                ('efficiency', models.IntegerField(help_text='Эффективность (%)')),
                ('gasket_hd', models.FloatField(help_text='Прокладка НД (дюймы)')),
                ('length', models.FloatField(help_text='Длина (дюймы)')),
                ('outer_seam_diameter', models.FloatField(help_text='Внешний Диаметр Шва (дюймы)')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='oil_filters/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manafacturers', to='main.manafacturer')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_types', to='main.filter_type')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
