# Generated by Django 5.1.6 on 2025-03-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brands_of_equipment_equipment_manafacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands_of_equipment',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='filter_type',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='manafacturer',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='oil_filter',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
