# Generated by Django 5.1.6 on 2025-03-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_products_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands_of_equipment',
            new_name='Brands_of_equipments',
        ),
        migrations.RenameModel(
            old_name='Equipment',
            new_name='Equipments',
        ),
        migrations.RenameModel(
            old_name='Filter_type',
            new_name='Filter_types',
        ),
        migrations.RenameModel(
            old_name='Manafacturer',
            new_name='Manafacturers',
        ),
    ]
