# Generated by Django 5.1.6 on 2025-03-10 05:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_brands_of_equipment_brands_of_equipments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands_of_equipments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='equipments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='filter_types',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manafacturers',
            options={},
        ),
        migrations.AddField(
            model_name='brands_of_equipments',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipments',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filter_types',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manafacturers',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
