# Generated by Django 5.1.6 on 2025-03-11 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_brands_of_equipments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands_of_equipments',
            options={'verbose_name_plural': 'Brands_of_equipments'},
        ),
        migrations.AlterModelOptions(
            name='equipments',
            options={'verbose_name_plural': 'Equipments'},
        ),
        migrations.AlterModelOptions(
            name='filter_types',
            options={'verbose_name_plural': 'Filter_types'},
        ),
        migrations.AlterModelOptions(
            name='manafacturers',
            options={'verbose_name_plural': 'Manafacturers'},
        ),
        migrations.AddField(
            model_name='filter_types',
            name='svg',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
