# Generated by Django 5.1.6 on 2025-03-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_brands_of_equipments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_types',
            name='parent',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
