# Generated by Django 5.1.6 on 2025-03-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_filter_types_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='article_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
