# Generated by Django 5.1.6 on 2025-03-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_products_article_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter_types',
            name='sub_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.filter_types'),
        ),
    ]
