# Generated by Django 5.1.6 on 2025-03-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_filter_types_sub_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter_types',
            name='sub_cat',
        ),
    ]
