# Generated by Django 5.1.6 on 2025-03-19 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_oformitproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OformitProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('oformit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.oformitproducts')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
        ),
        migrations.AddField(
            model_name='oformitproducts',
            name='products',
            field=models.ManyToManyField(through='main.OformitProductItem', to='main.products'),
        ),
    ]
