# Generated by Django 5.1.6 on 2025-03-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_subcategory_remove_filter_types_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
