# Generated by Django 5.1.6 on 2025-03-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_subcategory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter_types',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='filter_types',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='main.subcategory'),
        ),
    ]
