# Generated by Django 5.1.6 on 2025-03-23 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_filter_types_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_types',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='filters', to='main.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories_type', to='main.filter_types'),
            preserve_default=False,
        ),
    ]
