# Generated by Django 5.1.6 on 2025-03-23 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_filter_types_subcategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories_type', to='main.filter_types'),
        ),
    ]
