# Generated by Django 5.1.6 on 2025-03-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_subcategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_types',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='main.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
