# Generated by Django 5.1.6 on 2025-03-23 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_filter_types_subcategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='type',
            field=models.ForeignKey(db_column='type_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='main.filter_types'),
            preserve_default=False,
        ),
    ]
