# Generated by Django 5.1.6 on 2025-03-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_subcategory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='alt_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
