# Generated by Django 5.1.6 on 2025-03-24 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_products_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models_of_Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='main.brands_of_equipments')),
            ],
            options={
                'verbose_name_plural': 'Models_of_Brands',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='model',
            field=models.ForeignKey(blank=True, help_text='This is for only Brands category', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.models_of_brands'),
        ),
    ]
