# Generated by Django 5.1.6 on 2025-03-24 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_models_of_brands_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='models_of_brands',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='This is for only Equipments category', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.equipments'),
        ),
        migrations.AlterField(
            model_name='filter_types',
            name='subcategories',
            field=models.ManyToManyField(blank=True, help_text='If ', to='main.subcategory'),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='If subcategories have choose it', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subcategory'),
        ),
    ]
