# Generated by Django 5.1.6 on 2025-03-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_registeruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterUser',
        ),
    ]
